#!/bin/bash

# Header logging
e_header() {
	printf "\n$(tput setaf 7)%s$(tput sgr0)\n" "$@"
}

# Success logging
e_success() {
	printf "$(tput setaf 64)✓ %s$(tput sgr0)\n" "$@"
}

# Error logging
e_error() {
	printf "$(tput setaf 1)x %s$(tput sgr0)\n" "$@"
}

# Warning logging
e_warning() {
	printf "$(tput setaf 136)! %s$(tput sgr0)\n" "$@"
}

# Force create/replace the symlink.
link() {
    ln -fs "${1}" "${HOME}/${2}"
}

has() {
  [[ -x "$(command -v "$1")" ]];
}

has_not() {
  ! has "$1" ;
}
