#!/bin/bash

##############################################
# Start Editing here                         #
##############################################

# git configs
export GIT_USER="luanmuniz"
export GIT_NAME="Luan Muniz"
export GIT_EMAIL="luan@luanmuniz.com.br"

# Linux Configs
export COMPUTERNAME="Zimp Dev 1"
export LOCALHOSTNAME="zimp-dev-1"

# Set directorys Globals
export DF_GIT="https://github.com/${GIT_USER}/dotfiles-linux"
export PROJECTS_DIR="${HOME}/Projects"

##############################################
# You can stop Editing                       #
##############################################

export DF_DIR="${HOME}/.dotfiles"
source functions

if [[ ! -d ${DF_DIR} ]]; then

	e_header "Downloading dotfiles..."
	mkdir ${DF_DIR}

	curl -fsSLo ${HOME}/dotfiles.tar.gz "${DF_GIT}/tarball/master"
	mkdir ${HOME}/dotfiles-temp
	tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C "${HOME}/dotfiles-temp"

	rm -rf ${HOME}/dotfiles.tar.gz

	cd "${HOME}/dotfiles-temp"

else

	cd ${DF_DIR}
    git fetch
    git pull
	git checkout master
	e_success "Dotfiles update complete!"

	sleep 10
	sudo shutdown -r now

fi

e_header "Applying permissions on dotfiles folder"
sudo chmod -R 777 "${HOME}/dotfiles-temp"

# Create my Project folder
if [[ ! -d ${PROJECTS_DIR} ]]; then
	e_header "Creating Projects folder..."
	sudo mkdir ${PROJECTS_DIR}
fi

e_header "Applying permissions on Projects folder"
sudo chmod -R 777 ${PROJECTS_DIR}

e_header "Updating system"
sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y

source install/cli
source install/apps

source config/ssh-keys
source config/init

e_header "Updating dotfiles repository"
git clone "https://${GIT_USER}@github.com/${GIT_USER}/dotfiles" ${DF_DIR}
sudo chmod -R 777 ${DF_DIR}

# Copy `.gitconfig`.
# Any global git commands in `~/.bash_profile.local` will be written to
# `.gitconfig`. This prevents them being committed to the repository.
rsync -avz --quiet "${DF_DIR}/profile/gitconfig"  "${HOME}/.gitconfig"

# Create the necessary symbolic links between the `.dotfiles` and `HOME` directory.
# The `bash_profile` sources other files directly from the repository.
link "${DF_DIR}/profile/bashrc" ".bashrc"
link "${DF_DIR}/profile/bash_profile" ".bash_profile"
link "${DF_DIR}/profile/aliases" ".bash_aliases"
link "${DF_DIR}/profile/inputrc" ".inputrc"
link "${DF_DIR}/profile/gitattributes" ".gitattributes"
link "${DF_DIR}/profile/gitignore" ".gitignore_global"
link "${DF_DIR}/profile/gitconfig" ".gitconfig"

git config --global user.name $GIT_NAME
git config --global user.email $GIT_EMAIL

e_success "Dotfiles update complete!"
e_header "Removing temp folder and Restarting ..."

cd ..
rm "${HOME}/dotfiles-temp"

sleep 10
sudo shutdown -r now


