#!/bin/bash

set -eo pipefail

e_header "Installing Nylas Mail"
wget https://edgehill.nylas.com/download?platform=linux-deb -O ~/Downloads/nylas.deb
sudo dpkg --force-depends -i ~/Downloads/nylas.deb
sudo apt install -fy
rm ~/Downloads/nylas.deb

e_header "Installing Slack"
wget https://downloads.slack-edge.com/linux_releases/slack-desktop-2.6.3-amd64.deb -O ~/Downloads/slack.deb
sudo dpkg --force-depends -i ~/Downloads/slack.deb
sudo apt install -fy
rm ~/Downloads/slack.deb

e_header "Installing Slack"
wget https://go.skype.com/skypeforlinux-64.deb -O ~/Downloads/skype.deb
sudo dpkg --force-depends -i ~/Downloads/skype.deb
sudo apt install -fy
rm ~/Downloads/skype.deb

e_header "Installing Google Chrome"
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O ~/Downloads/chrome.deb
sudo dpkg --force-depends -i ~/Downloads/chrome.deb
sudo apt install -fy
rm ~/Downloads/chrome.deb

e_header "Installing Spotify"
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886 0DF731E45CE24F27EEEB1450EFDC8610341D9410
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt update && sudo apt install spotify-client

e_header "Installing Sublime Text 3"
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update && sudo apt install sublime-text

e_header "Installing VSCode"
wget "https://go.microsoft.com/fwlink/?LinkID=760868" -O ~/Downloads/vscode.deb
sudo dpkg --force-depends -i ~/Downloads/vscode.deb
sudo apt install -fy
rm ~/Downloads/vscode.deb

e_header "Installing Private Internet Access"
wget "wget https://www.privateinternetaccess.com/openvpn/openvpn.zip" -O ~/Downloads/openvpn.zip
sudo unzip ~/Downloads/openvpn.zip
